Repository paketo-buildpacks/liberty, pull requests merged in 2021-12, with the labels that each got.

#14 Update docs & sync with buildpack.toml entries
  README.md
  buildpack.toml
  helper/linker.go
Labels: type:documentation, semver:patch

#16 Switch to Go 1.16, which is what pipelines are using & bump buildpacks API to 0.7
  buildpack.toml
  go.mod
Labels: type:task, semver:patch

#17 Refactor detect & build
  README.md
  buildpack.toml
  cmd/buildpack/main.go
  cmd/helper/main.go
  cmd/update-buildpack-toml/main.go
  helper/init_test.go
  helper/linker.go
  helper/linker_test.go
  openliberty/build.go
  openliberty/build_test.go
  openliberty/detect.go
  openliberty/detect_test.go
  openliberty/distribution.go
  openliberty/distribution_test.go
  openliberty/init_test.go
Labels: semver:minor, type:enhancement

#18 Clean up output
  openliberty/build.go
  openliberty/build_test.go
Labels: type:bug, semver:patch

#19 Update dependencies
  buildpack.toml
Labels: type:dependency-upgrade, semver:patch

#9 Add `BP_INSTALL_TYPE` to configure install type
  README.md
  buildpack.toml
  helper/linker.go
  helper/linker_test.go
  openliberty/base.go
  openliberty/base_test.go
  openliberty/build.go
  openliberty/build_test.go
  openliberty/distribution_test.go
  openliberty/init_test.go
  openliberty/testdata/e71b55142699b277357d486eeb6244c71a0be3657a96a4286e30b27ceff34b17/stub-liberty-runtime.zip
  templates/app.tmpl
Labels: semver:minor, type:enhancement
