Repository paketo-buildpacks/liberty, pull requests merged in 2022-02, with the labels that each got.

#56 Use latest version
  buildpack.toml
Labels: type:dependency-upgrade, semver:patch

#51 Add packaged server support
  .gitignore
  README.md
  buildpack.toml
  helper/linker.go
  helper/linker_test.go
  internal/server/init_test.go
  internal/server/server.go
  internal/server/server_test.go
  internal/util/app.go
  internal/util/app_test.go
  internal/util/archive.go
  internal/util/archive_test.go
  internal/util/file.go
  internal/util/file_test.go
  internal/util/init_test.go
  internal/util/testdata/test.tar.gz
  internal/util/testdata/test.zip
  openliberty/base.go
  openliberty/base_test.go
  openliberty/build.go
  openliberty/build_test.go
  openliberty/detect.go
  openliberty/detect_test.go
  openliberty/distribution.go
  openliberty/distribution_test.go
  openliberty/feature.go
  openliberty/feature_test.go
Labels: semver:minor, type:enhancement

#68 Polishing commit
  buildpack.toml
  internal/util/archive.go
  openliberty/build.go
  openliberty/detect.go
  openliberty/distribution.go
  openliberty/feature.go
Labels: type:task, semver:patch

#67 Update buildpack.toml via new pipeline action
  .github/pipeline-descriptor.yml
Labels: type:task, semver:patch

#82 Polishing Commit
  cmd/main/main.go
  helper/linker.go
  helper/linker_test.go
  scripts/build.sh
Labels: type:bug, semver:patch
