Repository paketo-buildpacks/liberty, pull requests merged in 2022-08, with the labels that each got.

#218 Update Pipeline to 1.25.2
  .github/pipeline-version
  .github/workflows/pb-create-package.yml
  .github/workflows/pb-minimal-labels.yml
  .github/workflows/pb-synchronize-labels.yml
  .github/workflows/pb-tests.yml
  .github/workflows/pb-update-draft-release.yml
  .github/workflows/pb-update-go.yml
  .github/workflows/pb-update-open-liberty-runtime-full.yml
  .github/workflows/pb-update-open-liberty-runtime-jakartaee-9.yml
  .github/workflows/pb-update-open-liberty-runtime-javaee-8.yml
  .github/workflows/pb-update-open-liberty-runtime-kernel.yml
  .github/workflows/pb-update-open-liberty-runtime-micro-profile-3.yml
  .github/workflows/pb-update-open-liberty-runtime-micro-profile-4.yml
  .github/workflows/pb-update-open-liberty-runtime-micro-profile-5.yml
  .github/workflows/pb-update-open-liberty-runtime-web-profile-8.yml
  .github/workflows/pb-update-open-liberty-runtime-web-profile-9.yml
  .github/workflows/pb-update-pipeline.yml
Labels: type:task, semver:patch

#200 Move linker logic into build
  README.md
  buildpack.toml
  docs/using-liberty-stack.md
  helper/linker.go
  helper/linker_test.go
  internal/server/server.go
  internal/server/server_test.go
  internal/util/archive.go
  internal/util/archive_test.go
  liberty/base.go
  liberty/base_test.go
  liberty/build.go
  liberty/build_test.go
  liberty/distribution.go
  liberty/distribution_test.go
  liberty/feature.go
  liberty/feature_test.go
  liberty/testdata/060818cbcdc2008563f0f9e2428ecf4a199a5821c5b8b1dcd11a67666c1e2cd6/stub-external-configuration-with-directory.tar.gz
  liberty/testdata/6be374a1c3eeda98effb66fe7f9feb48ffcf325492237bc717c77794566f8ce0.toml
  liberty/testdata/6be374a1c3eeda98effb66fe7f9feb48ffcf325492237bc717c77794566f8ce0/stub-external-configuration-with-directory.tar.gz
  liberty/testdata/test.war
  templates/default-http-endpoint.tmpl
  templates/expose-default-endpoint.xml
  templates/server.tmpl
Labels: type:enhancement, semver:major

#221 Add WebSphere Liberty distribution
  .github/pipeline-descriptor.yml
  .github/workflows/pb-update-websphere-liberty-runtime-jakartaee-9.yml
  .github/workflows/pb-update-websphere-liberty-runtime-javaee-7.yml
  .github/workflows/pb-update-websphere-liberty-runtime-javaee-8.yml
  .github/workflows/pb-update-websphere-liberty-runtime-kernel.yml
  .github/workflows/pb-update-websphere-liberty-runtime-web-profile-7.yml
  .github/workflows/pb-update-websphere-liberty-runtime-web-profile-8.yml
  .github/workflows/pb-update-websphere-liberty-runtime-web-profile-9.yml
  README.md
  buildpack.toml
  liberty/build.go
  liberty/build_test.go
Labels: semver:minor, type:enhancement

#257 Implement RFC 0050: Rename Buildpack
  README.md
  buildpack.toml
Labels: type:task, semver:patch
