Repository paketo-buildpacks/liberty, pull requests merged in 2022-10, with the labels that each got.

#288 Do not list hidden directories in usr/servers
  internal/server/server.go
  internal/server/server_test.go
Labels: type:bug, semver:patch

#285 Enable verbose gc logging
  internal/util/init_test.go
  internal/util/jvm.go
  internal/util/jvm_test.go
  liberty/base.go
  liberty/base_test.go
  liberty/build.go
  liberty/build_test.go
Labels: semver:minor, type:enhancement

#298 Update instructions for creating stacks
  docs/using-liberty-stack.md
Labels: type:documentation, semver:patch
