Repository paketo-buildpacks/liberty, pull requests merged in 2022-03, with the labels that each got.

#71 first pass at renaming repo
  .github/pipeline-descriptor.yml
  .github/workflows/create-package.yml
  .gitignore
  NOTICE
  README.md
  buildpack.toml
  cmd/helper/main.go
  cmd/main/main.go
  docs/using-liberty-stack.md
  go.mod
  helper/linker.go
  helper/linker_test.go
  internal/server/server.go
  internal/server/server_test.go
  internal/util/app_test.go
  internal/util/archive_test.go
  internal/util/file_test.go
  liberty/base.go
  liberty/base_test.go
  liberty/build.go
  liberty/build_test.go
  liberty/detect.go
  liberty/detect_test.go
  liberty/distribution.go
  liberty/distribution_test.go
  liberty/feature.go
  liberty/feature_test.go
  liberty/init_test.go
  liberty/testdata/060818cbcdc2008563f0f9e2428ecf4a199a5821c5b8b1dcd11a67666c1e2cd6.toml
  liberty/testdata/060818cbcdc2008563f0f9e2428ecf4a199a5821c5b8b1dcd11a67666c1e2cd6/stub-external-configuration-with-directory.tar.gz
  liberty/testdata/e71b55142699b277357d486eeb6244c71a0be3657a96a4286e30b27ceff34b17.toml
  liberty/testdata/e71b55142699b277357d486eeb6244c71a0be3657a96a4286e30b27ceff34b17/stub-liberty-runtime.zip
  scripts/build.sh
Labels: semver:minor, type:task

#94 Uses a more specific regex to match CPE & PURL during udpates
  .github/pipeline-descriptor.yml
  .github/workflows/update-open-liberty-runtime-full.yml
  .github/workflows/update-open-liberty-runtime-jakartaee-9.yml
  .github/workflows/update-open-liberty-runtime-javaee-8.yml
  .github/workflows/update-open-liberty-runtime-kernel.yml
  .github/workflows/update-open-liberty-runtime-micro-profile-3.yml
  .github/workflows/update-open-liberty-runtime-micro-profile-4.yml
  .github/workflows/update-open-liberty-runtime-micro-profile-5.yml
  .github/workflows/update-open-liberty-runtime-web-profile-8.yml
  .github/workflows/update-open-liberty-runtime-web-profile-9.yml
Labels: type:bug, semver:patch

#96 Bump to using Go 1.17 and fix module with major version suffix
  go.mod
  go.sum
Labels: semver:minor, type:dependency-upgrade

#98 Server should listen on all interfaces.
  buildpack.toml
  helper/linker.go
  helper/linker_test.go
  templates/default-http-endpoint.tmpl
Labels: type:bug, semver:patch

#93 Implement RFC 0008 & BP_JAVA_APP_SERVER Support
  README.md
  buildpack.toml
  docs/using-liberty-stack.md
  liberty/base.go
  liberty/build.go
  liberty/build_test.go
  liberty/detect.go
  liberty/detect_test.go
Labels: semver:minor, type:enhancement

#101 Add missing copyright statement
  cmd/helper/main.go
  cmd/main/main.go
  helper/init_test.go
  helper/linker.go
  helper/linker_test.go
  internal/core/buildsrc.go
  internal/core/buildsrc_test.go
  internal/core/init_test.go
  internal/server/init_test.go
  internal/server/server.go
  internal/server/server_test.go
  internal/util/app.go
  internal/util/app_test.go
  internal/util/archive.go
  internal/util/archive_test.go
  internal/util/file.go
  internal/util/file_test.go
  internal/util/init_test.go
  liberty/base_test.go
  liberty/build.go
  liberty/build_test.go
  liberty/detect.go
  liberty/detect_test.go
  liberty/distribution.go
  liberty/distribution_test.go
  liberty/feature.go
  liberty/feature_test.go
  liberty/init_test.go
Labels: type:task, semver:patch

#111 Implements RFC 0008 & `BP_JAVA_APP_SERVER` for Liberty
  README.md
  buildpack.toml
  helper/linker_test.go
  internal/core/buildsrc.go
  internal/core/buildsrc_test.go
  liberty/build.go
  liberty/build_test.go
  liberty/detect.go
  liberty/detect_test.go
Labels: semver:minor, type:enhancement

#123 Adding support to install features and fixes
  README.md
  buildpack.toml
  cmd/main/main.go
  docs/installing-ifixes.md
  docs/using-liberty-stack.md
  go.mod
  internal/server/server.go
  internal/server/server_test.go
  liberty/base.go
  liberty/base_test.go
  liberty/build.go
  liberty/build_test.go
  liberty/distribution.go
  liberty/distribution_test.go
Labels: semver:minor, type:enhancement

#124 Clarify instructions on installing features in README
  README.md
Labels: type:documentation, semver:patch

#136 adding BP_JAVA_APP_SERVER=liberty to examples
  README.md
  docs/installing-ifixes.md
Labels: type:documentation, semver:patch

#138 Check if build runs earlier
  liberty/build.go
Labels: type:bug, semver:patch
