Repository paketo-buildpacks/liberty, pull requests merged in 2022-01, with the labels that each got.

#21 Add doc on using Liberty stack
  docs/using-liberty-stack.md
Labels: type:documentation, semver:patch

#25 Include app template in packaging
  buildpack.toml
Labels: type:bug, semver:patch

#27 Create config overrides directory if needed
  helper/linker.go
Labels: type:bug, semver:patch

#29 Ensure Java is available at build and launch
  helper/linker.go
  openliberty/build.go
  openliberty/detect.go
  openliberty/detect_test.go
  openliberty/distribution.go
  openliberty/distribution_test.go
Labels: type:bug, semver:patch

#23 Allow custom jar user features to be installed
  README.md
  buildpack.toml
  go.mod
  helper/linker.go
  helper/linker_test.go
  internal/util/file.go
  openliberty/base.go
  openliberty/base_test.go
  openliberty/build.go
  openliberty/build_test.go
  openliberty/feature.go
  openliberty/feature_test.go
  openliberty/init_test.go
  openliberty/testdata/060818cbcdc2008563f0f9e2428ecf4a199a5821c5b8b1dcd11a67666c1e2cd6.toml
  openliberty/testdata/060818cbcdc2008563f0f9e2428ecf4a199a5821c5b8b1dcd11a67666c1e2cd6/stub-external-configuration-with-directory.tar.gz
  templates/features.tmpl
Labels: semver:minor, type:enhancement

#35 Add CI & missing profiles
  .github/pipeline-descriptor.yml
  .github/workflows/update-open-liberty-runtime-full.yml
  .github/workflows/update-open-liberty-runtime-jakartaee-9.yml
  .github/workflows/update-open-liberty-runtime-javaee-8.yml
  .github/workflows/update-open-liberty-runtime-kernel.yml
  .github/workflows/update-open-liberty-runtime-micro-profile-3.yml
  .github/workflows/update-open-liberty-runtime-micro-profile-4.yml
  .github/workflows/update-open-liberty-runtime-micro-profile-5.yml
  .github/workflows/update-open-liberty-runtime-web-profile-8.yml
  .github/workflows/update-open-liberty-runtime-web-profile-9.yml
  buildpack.toml
  cmd/update-buildpack-toml/main.go
  go.mod
  go.sum
Labels: type:task, semver:patch
